Repository minecraft-initiative/UniversalFriends, pull requests merged in 2019-12, with the labels that each got.

#13 Added some documentation to classes to make it easier to understand.
  src/main/java/me/ironexception/universalfriends/association/Association.java
  src/main/java/me/ironexception/universalfriends/json/PersonLoader.java
  src/test/java/me/ironexception/universalfriends/association/AssociationTest.java
Labels: documentation, enhancement

#17 Operations
  src/main/java/me/ironexception/universalfriends/configuration/Configuration.java
  src/main/java/me/ironexception/universalfriends/configuration/Operations.java
  src/main/java/me/ironexception/universalfriends/json/PersonLoader.java
  src/test/java/me/ironexception/universalfriends/json/PersonLoaderTest.java
Labels: new-feature

#23 Separate libraries
  UniversalFriends-core/build.gradle
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/Standard.java
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/association/Association.java
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/configuration/Configuration.java
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/configuration/Operations.java
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/json/Bounds.java
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/json/FriendFileLoader.java
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/json/FriendFileLoaderException.java
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/person/IPerson.java
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/person/Person.java
  UniversalFriends-core/src/test/java/me/ironexception/universalfriends/TestUtil.java
  UniversalFriends-core/src/test/java/me/ironexception/universalfriends/association/AssociationTest.java
  UniversalFriends-core/src/test/java/me/ironexception/universalfriends/configuration/OperationsTest.java
  UniversalFriends-core/src/test/java/me/ironexception/universalfriends/json/FriendFileLoaderTest.java
  UniversalFriends-core/src/test/resources/friends.json
  UniversalFriends-core/src/test/resources/friends_operations.json
  UniversalFriends-core/src/test/resources/friends_with_meta.json
  UniversalFriends-minecraft/build.gradle
  UniversalFriends-minecraft/src/main/java/me/ironexception/universalfriends/GameProfilePerson.java
  UniversalFriends-minecraft/src/main/java/me/ironexception/universalfriends/UniversalFriends.java
  build.gradle
  settings.gradle
  src/main/java/me/ironexception/universalfriends/json/PersonLoader.java
  src/main/java/me/ironexception/universalfriends/json/PersonLoaderException.java
  src/test/java/me/ironexception/universalfriends/json/PersonLoaderTest.java
Labels: building, enhancement

#27 Feature/selectors
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/association/Association.java
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/configuration/Operations.java
  UniversalFriends-core/src/main/java/me/ironexception/universalfriends/select/Selector.java
  UniversalFriends-core/src/test/java/me/ironexception/universalfriends/association/AssociationTest.java
  UniversalFriends-core/src/test/java/me/ironexception/universalfriends/configuration/OperationsTest.java
  UniversalFriends-core/src/test/java/me/ironexception/universalfriends/select/SelectorTest.java
  UniversalFriends-core/src/test/resources/friends_selections.json
  UniversalFriends-minecraft/src/main/java/me/ironexception/universalfriends/UniversalFriends.java
Labels: new-feature
